---

services:
  backend:
    build: ./backend
    container_name: pong_backend
    restart: always
    env_file:
      - .env
    expose:
      - "${BACKEND_PORT}"
    depends_on:
      - db
    volumes:
      - django-admin:/app/staticfiles
      - django-media:/app/media
      - ./blockchain:/app/blockchain
    ports:
      - "${BACKEND_PORT}:8000"
    networks:
      - transcendence_net

  frontend:
    build:
      context: ./frontend
#      dockerfile: Dockerfile-ultimate     # uncomment this line for the utimate most optimized Dockerfile
#      dockerfile: Dockerfile-dev         # uncomment this line for Hot-Reload Frontend
#    volumes:                             # uncomment this line for Hot-Reload Frontend
#      - ./frontend/src:/app/src          # uncomment this line for Hot-Reload Frontend
#      - ./frontend/public:/app/public    # uncomment this line for Hot-Reload Frontend
    container_name: pong_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    networks:
      - transcendence_net

  db:
    image: postgres:17.1-alpine3.19
    container_name: pong_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - transcendence_net

  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    container_name: pong_pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - transcendence_net

  nginx:
    image: nginx:1.26-alpine
    container_name: pong_nginx
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs
      - django-admin:/app/staticfiles
      - django-media:/app/media
    networks:
      - transcendence_net

volumes:
  pgdata:
  pgadmin_data:
  django-admin:
  django-media:

networks:
  transcendence_net:
    driver: bridge
